# Generated by Django 3.0.3 on 2020-05-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='liked_num',
            new_name='liked_time',
        ),
    ]
