# Generated by Django 3.0.3 on 2020-05-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200502_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
